export const actionTypes = {
  apiSuccess: "apiSuccess",
  apiFailed: "apiFailed",
  loading: "loading",
  userLoaded: "userLoaded",
  userLoadedError: "userLoadedError",
  userLoggedIn: "userLoggedIn",
  addSection: "addSection",
  setClassroomStates: "setClassroomStates",
  studentFeedLoaded: "studentFeedLoading",
  teacherFeedLoaded: "teacherFeedLoaded",
  sectionMembersLoaded: "sectionMembersLoaded",
  classroomMembersLoaded: "classroomMembersLoaded",
  userLogout: "userLogout",
  sectionLoaded: "sectionLoaded",
  unauthorizedVisit: "unauthorizedVisit",
  sectionLoadFailed: "sectionLoadFailed",
  announcementPosted: "announcementPosted",
  announcementLoaded: "announcementLoaded",
  commentAdded: "commentAdded",
  getCategories: "getCategories",
};
