FROM node:16-alpine3.12 AS builder
ENV repository=application
COPY --from=codepuller /${repository} /${repository}
WORKDIR /${repository}/frontend/
RUN npm install
EXPOSE 3000
CMD ["npm", "run", "dev"]
