pipeline {

  agent {
    kubernetes {
      yamlFile 'pipelineAgent.yaml'   
    }
  }

  stages {

    stage('Build & Push Images Using Google Kaniko') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`../backend/dockerfile --context `pwd` \
                             --destination=tashikmoin/codeclassy-backend:${BUILD_NUMBER};
            /kaniko/executor --dockerfile `pwd`../frontend/dockerfile --context `pwd` \
                             --destination=tashikmoin/codeclassy-frontend:${BUILD_NUMBER};
            '''
          }
        }
      }
    }

    stage('Deploy App to Kubernetes') {     
      steps {
        container('kubectl') {
          withCredentials([file(credentialsId: 'k8credid', variable: 'KUBECONFIG')]) {
            // sh 'sed -i "s/<TAG>/${BUILD_NUMBER}/" nginx.yaml'
            // sh 'kubectl apply -f nginx.yaml -n default'
            sh 'echo HelloWorld!'
          }
        }
      } 
    }
  
  }
}