pipeline {

  agent {
    kubernetes {
      yamlFile 'jenkins/pipelineAgent.yaml'   
    }
  }

  stages {

    stage('Building & Pushing Frontend Image To DockerHub Registry') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile frontend/dockerfile.prod \
                             --destination=tashikmoin/codeclassy-frontend:${BUILD_NUMBER};
            '''
          }
        }
      }
    }

    stage('Building & Pushing Backend Image To DockerHub Registry') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile backend/dockerfile.prod \
                             --destination=tashikmoin/codeclassy-backend:${BUILD_NUMBER};
            '''
          }
        }
      }
    }

    stage('Deploy App to Kubernetes') {     
      steps {
        container('kubectl') {
          withCredentials([file(credentialsId: 'k8credid', variable: 'KUBECONFIG')]) {
            // sh 'sed -i "s/<TAG>/${BUILD_NUMBER}/" nginx.yaml'
            // sh 'kubectl apply -f nginx.yaml -n default'
            sh 'echo HelloWorld!'
          }
        }
      } 
    }
  
  }
}