apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kubectl
      image: joshendriks/alpine-k8s
      command:
        - /bin/cat
      tty: true

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
      # IMPORTANT NOTE
      # DO NOT FORGET TO CREATE THIS APPLICATION SECRET INSIDE JENKINS NAMESPACE OF YOUR K8 CLUSTER.
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: application-secrets # <name of the secret object here>
              key: username # <key name inside secret object without "">
        - name: githubsecret
          valueFrom:
            secretKeyRef:
              name: application-secrets # <name of the secret object here>
              key: githubsecret # <key name inside secret object without "">
        - name: repository
          valueFrom:
            secretKeyRef:
              name: application-secrets # <name of the secret object here>
              key: repository # <key name inside secret object without "">
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker

  volumes:
    - name: kaniko-secret # volume for docker secrets
      secret:
        secretName: regcred # data on this volume will come from regcred kubernetes secret.
        items:
          - key: .dockerconfigjson
            path: config.json
