apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kubectl
      image: joshendriks/alpine-k8s
      command:
        - /bin/cat
      tty: true

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      resources:
        limits:
          memory: "2Gi"
      command:
        - /busybox/cat
      tty: true
      # IMPORTANT NOTE
      # DO NOT FORGET TO CREATE THIS APPLICATION SECRET INSIDE JENKINS NAMESPACE OF YOUR K8 CLUSTER.
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker

  volumes:
    - name: kaniko-secret # volume for docker secrets
      secret:
        secretName: regcred # data on this volume will come from regcred kubernetes secret.
        items:
          - key: .dockerconfigjson
            path: config.json
