apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      name: admin-console-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: admin-console-pod-label
    spec:
      containers:
        - name: admin-console-container
          image: convergencelabs/convergence-admin-console:1.0.0-rc.12
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https


# env 
#     environment:
#       CONVERGENCE_SERVER_REALTIME_API: "https://localhost/realtime/"
#       CONVERGENCE_SERVER_REST_API: "https://localhost/rest/"
#       CONVERGENCE_CONSOLE_BASE_URL: "/console/"
