apiVersion: v1
kind: Service
metadata:
  name: admin-console
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: admin-console-pod-label
  type: ClusterIP 
