apiVersion: v1
kind: Service
metadata:
  name: admin-console
  namespace: default
spec:
  ports:
    - port: 
      protocol: TCP
      targetPort: 
  selector:
    name: admin-console-pod-label
  type: ClusterIP 
