apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  ports:
    - port: 5000 # outside pod internally this service will be accessed using 5000 port.
      protocol: TCP
      targetPort: 5000
  selector:
    name: backend-pod-label
  type: LoadBalancer # internal service
