apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-seed-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      name: cluster-seed-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: cluster-seed-pod-label
    spec:
      containers:
        - name: cluster-seed-container
          image: convergencelabs/convergence-cluster-seed:1.0.0-rc.12
          command: ["/bin/sh", "-c"]
          args:
            - -Dlog4j.configurationFile=/etc/convergence/log4j2.xml;
          ports:
            - containerPort: 25520


# env 
#     environment:
#       JAVA_OPTS: "-Xmx64m -Xss512k -XX:CICompilerCount=1 -XX:-TieredCompilation"
#       REMOTING_EXTERNAL_HOSTNAME: cluster-seed
#       CLUSTER_SEED_NODES: cluster-seed


# persist 
# :/etc/convergence/log4j2.xml