apiVersion: v1
kind: Service
metadata:
  name: cluster-seed-service
  namespace: default
spec:
  ports:
    - port: 25520
      protocol: TCP
      targetPort: 25520
  selector:
    name: cluster-seed-pod-label
  type: ClusterIP 
