apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-seed-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cluster-seed-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: cluster-seed-pod-label
    spec:
      containers:
        - name: cluster-seed-container
          image: cluster-seed
          ports:
            - containerPort: 
