apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: default
spec:
  ports:
    - name: mysql
      port: 3306 # outside pod internally this service will be accessed using 5000 port.
      protocol: TCP
      targetPort: 3306
  selector:
    name: database-pod-label
  type: ClusterIP # internal service
