apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      name: database-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: database-pod-label
    spec:
      containers:
        - name: database-container
          image: mysql
          ports:
            - containerPort: 3306
