apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: database-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: database-pod-label
    spec:
      containers:
        - name: database-container
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets # <name of the secret object here>
                  key: MYSQL_ROOT_PASSWORD # <key name inside secret object without "">

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secrets # <name of the secret object here>
                  key: MYSQL_DATABASE # <key name inside secret object without "">
