apiVersion: v1
kind: Service
metadata:
  name: monaco-editor
  namespace: default
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    name: monaco-editor-pod-label
  type: ClusterIP 
