apiVersion: apps/v1
kind: Deployment
metadata:
  name: monaco-editor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: monaco-editor-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: monaco-editor-pod-label
    spec:
      containers:
        - name: monaco-editor-container
          image: tashikmoin/codeclassy-monaco-editor:<build-no>
          ports:
            - containerPort: 4000

