apiVersion: apps/v1
kind: Deployment
metadata:
  name: orientdb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: orientdb-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: orientdb-pod-label
    spec:
      containers:
        - name: orientdb-container
          image: orientdb:3.0.37
          ports:
            - containerPort: # <port>

# persist 
# :/orientdb/databases
# :/orientdb/backup


# environment:
#   ORIENTDB_ROOT_PASSWORD: "password"
#   ORIENTDB_OPTS_MEMORY: "-Xms384m -Xmx384m"
#   JAVA_OPTS: "-Dstorage.wal.allowDirectIO=false"