apiVersion: v1
kind: Service
metadata:
  name: orientdb
  namespace: default
spec:
  ports:
    - port: 2480
      protocol: TCP
      targetPort: 2480
    - port: 2424
      protocol: TCP
      targetPort: 2424
  selector:
    name: orientdb-pod-label
  type: ClusterIP 
