apiVersion: apps/v1
kind: Deployment
metadata:
  name: orientdb-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      name: orientdb-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: orientdb-pod-label
    spec:
      volumes:
        - name: codeclassy
          configMap:
            name: codeclassy-configmap 
      volumes:
        - name: codeclassy-volume
          persistentVolumeClaim:
            claimName: codeclassy-pvc
      containers:
        - name: orientdb-container
          image: orientdb:3.0.37
          ports:
            - containerPort: 2424
              name: orient-db
            - containerPort: 2480
              name: default-orient-db
          volumeMounts:
            - name: codeclassy-volume
              mountPath: "/orientdb/databases"
            - name: codeclassy-volume
              mountPath: "/orientdb/backup"
          volumeMounts:
            - name: codeclassy
              mountPath: "/codeclassy" 
          env:
            - name: ORIENTDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: codeclassy-configmap 
                  key: ORIENTDB_ROOT_PASSWORD

            - name: ORIENTDB_OPTS_MEMORY
              valueFrom:
                configMapKeyRef:
                  name: codeclassy-configmap 
                  key: ORIENTDB_OPTS_MEMORY

            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: codeclassy-configmap 
                  key: JAVA_OPTS
