apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: proxy-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: proxy-pod-label
    spec:
      containers:
        - name: proxy-container
          image: nginx:1.21.1-alpine
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https

# persist
# /etc/nginx/conf.d/default.conf
# /usr/share/nginx/html
# /etc/nginx/ssl/
