apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: rabbitmq-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: rabbitmq-pod-label
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq
          ports:
            - containerPort: 
