apiVersion: v1
kind: Service
metadata:
  name: rce-server
  namespace: default
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    name: rce-server-pod-label
  type: ClusterIP 
