apiVersion: apps/v1
kind: Deployment
metadata:
  name: rce-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: rce-server-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: rce-server-pod-label
    spec:
      containers:
        - name: rce-server-container
          image: tashikmoin/codeclassy-rce-server:<build-no>
          ports:
            - containerPort: 7000
