apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: default
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: redis-pod-label
  type: ClusterIP 
