apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      name: server-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: server-pod-label
    spec:
      containers:
        - name: server-container
          image: convergencelabs/convergence-server:1.0.0-rc.12
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 25520
              name: seed


# persist 
# :/opt/convergence-server/conf/log4j2.xml
# :/opt/convergence-server/conf/convergence-server.conf