apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
spec:
  ports:
    - port: 
      protocol: TCP
      targetPort: 
  selector:
    name: server-pod-label
  type: ClusterIP 
