apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: worker-pod-label
    spec:
      containers:
        - name: worker-container
          image: worker
          ports:
            - containerPort: 
