apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    - port: 443
      protocol: TCP
      targetPort: 443
    - port: 43995
      protocol: TCP
      targetPort: 43995
    - port: 46465
      protocol: TCP
      targetPort: 46465
  selector:
    name: worker-pod-label
  type: ClusterIP 
