apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      name: worker-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: worker-pod-label
    spec:
      containers:
        - name: worker-container
          image: tashikmoin/codeclassy-worker:<build-no>
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 43995
              name: servicex
              protocol: TCP
            - containerPort: 46465
              name: servicey
              protocol: UDP
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "1"
          args:
          - -cpus
          - "1"
